### ISSUE TITLE
Updating tests to handle nutrient Components

### ISSUE THREAD

**Issue by mattjbr123** [unifhy-org/unifhy#93]
Sub-task of #14 

As part of #14 the unit tests for UNIFHY need to be updated to expect nutrient components before any development on UNIFHY to add these components takes place.

**Comment by mattjbr123** [comment]
There is some question on whether or not to make the nutrient components mandatory or not for the tests (and thus for the user). 
As UNIFHY allows NullComponents, which essentially remove the component from the Model, I think for now we will require all 6 components be provided for a Model, as the user will have the option of making the nutrient components NullComponents if they do not wish to model nutrients.

**Comment by mattjbr123** [comment]
**I am in the process of adapting this from hand-written notes so it's a bit of a mess right now, this will change...**

The following changes need to be made to the tests for them to require 6 components instead of 3:

test_model.py:
- Simulator.from_scratch(): Add 3 extra arguments defining the 'category' of the nutrient Components in the function declaration and to all calls of the function, and edit the body of the function appropriately to process these [BE MORE SPECIFIC]
- Simulator.setup_model(): Add 3 extra arguments defining the nutrient Component 'kinds' to the function declaration and function calls, and add 'get-dummy. component' calls for nutrients Components as for the WaterEnergy Components to the body of the function
- Add nutrient component folders in unifhy/tests/tests/components for nutrient components, like for the WaterEnergy components. Each folder needs to contain an
- init-.. py file with just `from. dummy import Dummy` in it.
- a component_name.py file that replicates the equivalent WaterEnergy Component in all but name (except perhaps for the dummy C and dummy Fortran bits which can be done later?)
- The class that Dummy subclasses (one of the NutrientSurface, NutrientSubsurface or NutrientOpenwater classes) will not exist yet causing the test to fail as expected.

Add some WE4N transfers into the dummy component files.
(or some for later in the name of keeping the changes as
small as possible in line w/unit-testing Pandian
Create dummy data to fit the tests. I e. w/the inputs
specified in the dummy nutrients components. Copying the
existing files e adding/removing/changing the names of the data
variables as needed should do the trick.
Add these/any new input variables to the 'science ishdriving-
data-daily too. no Modify calls to to unde arguments
that are the
nutrients components, e the
names identifier to include these as well.
unity. Model
Extend
clean-up. dump-files C)e clean-up. record-files () in test. M py to
include nutrients components directories files
3
Add simulator-2. model. nutrient layer
initialise-states-from-dump lines (triggering an expected
FAIL in
tests pinup-dump. init spiny
)
Add nutrient model comps (as model. nutrallayer) in
check-fuel.
conditions
add transfers tobop over transfers in
check-exchangers
transfers
The transfers add blown components.
0 add are
any you
involving the new nutrient components, defied in tests/tests/
components/layernamel dummy. py
Add nutrients components to you files in tests
lionfigurations, copying the time e space setup from the WE
comps, and the transfers/datasets/ params ete. from the
dummy comps.
we
Add in c d n in selector for the 3 nutrient components e the
N comps to ideepcopy following loop, add a sub est, calls I add
assertive compare states test for N comps in
Advanced Test Model.test-set up, spiny, simulate-resumeall(
still in test-d. py).
In the Basket Model vision, add in 3 dee.pespyknes.se
compare-states lies for the mutant comps.
In Busiest Model. check-fat cords 0 add in the 3 N comps to
theloop over components
Busiest Model. check-records 4In
do the same.
Add u c d n in doe selector
N comps for 3 N comps i add to subtlest callfor
Add 'Python, "Fortran, 'c' for 3 N comps is doe selector, add
them to subsequent for loop e add to subtlest call for
test-setup, simulate ()
test-setup, simulate vinous-sources C)
test-component. PyIn the various dictionaries, add entries for
the 3 N components
Matching the setup of the WE comps should do the job for now,
though . might want to build an additional test for doffs blown
matching comps of Weed in the future. Might need to create
new dummy-subsurface-parameter.... or similar, files.
Add unphy. component. nutrient compname to the sibling
class loop intest. instantiation-datacomponentCausing an
expected FAIL as
these won't exist get
Same
test. instantiation-mleomponettfor
test-clock.py
Add the 3 mutant comps to the
test-clock.int C)of s e to the assert Equal statements below. this
will cause an expected FAIL as Clock will not have been set up
to expect N comps.start
Repeat for
Repeat for
test-clock iteration ()test-clock-incompatible,time-domains ()
Repeat for
test-clock-incompatible,dumping-frequency (
Ed-a
{
lap, boot like a e z
correspond to the test resolutions set up in test-time. py. If testtime-
py is changed, will need to change the above variables
here
tests record PY
add in the expected records for the snow nut. comps for the
same-t e diff-t tests, like for the Wt comps. This will depend on
the values in the input files easy processing in the dummy
comps

**Comment by mattjbr123** [comment]
Regarding the structure of the new dummy components. I have settled upon the setup shown in the diagram below. The key features are:
- Replication of the transfers between WaterEnergy Components in the Nutrient Components, with different names assigned to avoid ambiguity and errors
- The addition of two transfers between the WaterEnergy set of Components and the Nutrient set of Components.

The two transfers added are:
- From the Nutrient SurfaceLayer Component to the WaterEnergy SurfaceLayer Component (transfer_h)
- From the WaterEnergy OpenWater Component to the Nutrient OpenWater Component (transfer_p)

To accommodate these transfers the following edits were made to the WaterEnergy Components:
- OpenWater Component: transfer_p set to first division and current timestep of state_a
- SurfaceLayer Component: new output_y created which is transfer_h multiplied by the current timestep of state_a

The Nutrient Components are copies of the WaterEnergy components with only the transfer names changed as shown in the diagram below. The edits then made to accommodate the two new transfers added are:
- OpenWater Component: transfer_p added to output_y
- SurfaceLayer Component: transfer_h set to first timestep of state_a multiplied by ancillary_e

![Scratch - page 5](https://github.com/unifhy-org/unifhy/assets/47819526/ea5d9d5f-6f74-450a-8fe4-02c244f77e6a)

**Comment by ThibHlln** [comment]
Hi Matt, 

For the dummy files, you may find these scripts useful (I hope): https://github.com/hydro-jules/data-generators

As you will have noticed, I tried to keep the "equations" in the dummy components as simple as possible while using each input/transfer/parameter/state/constant at least once. This meant that the time series the components were producing were mostly made of integers or at least rational numbers (see https://github.com/unifhy-org/unifhy/blob/4105932ed7dfec34d428c1f2d2f85ec25ea522ed/tests/tests/test_utils/test_record.py#L10C6-L59 and https://github.com/hydro-jules/data-generators/blob/a4667021f7f0e4c9edf32eacd40f0d3394ce71c9/generate_dummy_cf_substitute_data.py#L35-L66). This was to avoid having to deal with floating point precision when comparing what was produced by the components vs. what I was expecting on paper. Since you are necessarily adding transfers between WaterEnergy and Nutrient, you will have to increase the "complexity" of these "equations", so you may not be able to avoid ending up with irrational numbers, but I guess it is not too bad.

**Comment by mattjbr123** [comment]
Thanks Thibault :)
I was aware of this issue of possible irrational numbers, so I tried to keep the extra calculations as simple as possible but didn't actually check what the records would now come out as. 
That's my next job xD

It looks like I don't have access to the data-generators repo - I'm just getting a 404

**Comment by mattjbr123** [comment]
Addding in the expected records for the 3 nutrient Components for the
[same_t](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py#L11) and [diff_t](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py#L35) tests to [test_record.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py) took a long time due to the need to calculate 16 model timesteps by hand, with 6 components. 

To ease this process for future development I intend to create a script that users can trust to calculate these values for them once they input dummy components. See issue

**Comment by mattjbr123** [comment]
Test updates (finally!) complete. 
Next step is to analyse which of these changes will result in the errors when the full framework is run and make changes to the framework to allow the tests to pass.

**Comment by mattjbr123** [comment]
The following changes need to be made to the tests when adding a new Component to the framework:

### [test_model.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py):
- [x] [**Simulator.from_scratch()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L27): Add an extra argument defining the 'category' of the new Component in the function declaration and to all calls of the function, and edit the body of the function appropriately to process these 
- [x] [**Simulator.setup_model()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L48): Add an extra argument defining the new Component 'kind' to the function declaration and all function calls, and add a `get_dummy_component()` call for the new Component as for the other Components to the body of the function
- [x] Modify all calls to **unifhy.Model()** to include a new argument that is the new Component, and modify the identifier (within the function body?) to include this as well. 
- [x] Extend [**clean_up_dump_files()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L121)  and [**clean_up_record_files()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L146) to include the new Component directories and files
- [x] Add  `simulator_2.model**.xxxxxyyyyy**.initialise_states_from_dump` lines to the [**test_spinup_dump_init_spinup()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L220) test
- [x] Add the new Component (as model.xxxxxyyyyy) in [**check_final_conditions()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L473)
- [x] Add transfers to loop over in [**check_exchanger_transfers()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L516). The transfers to add are any added between Components involving a new dummy Component defined in [tests/tests/components](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/components)/componentname/dummy.py
- [x] In [**AdvancedTestModel.test_setup_spinup_simulate_resume_run()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L579): add in 'c', 'd' and 'n' in the 'doe' (design of experiment) selector variable for the new Component and the following loop, add the new Component to subtest and deepcopy calls, and add assertTrue() to compare states tests for the new Component. 
- [x] In [**BasicTestModel.test_setup_spinup_simulate_resume_run()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L405), add in a deepcopy line and compare_states line for the new Component.
- [x] In [**BasicTestModel.check_records()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L530) add in the new Component to the loop over Components
- [x] In [**AdvancedTestModel.test_setup_simulate()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L660): add 'c', 'd' and 'n' to the 'doe' selector variable for the new Component and add to subTest call 
- [x] In [**AdvancedTestModel.test_setup_simulate_various_sources()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_model.py#L704): add 'Python', 'Fortran', 'c' for the new Component in the 'doe' selector variable, add them to subsequent for loop and add to subTest call 

### [test_component.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_component.py)
- [x] In the various dictionaries, add entries for the new Component. 
- [x] Add `unifhy.component. **XxxxxYyyyy**` to the substituting class loop in [**test_instantiation_datacomponent()** ](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_component.py#L221)
- [x] Do the same for [**test_instantiation_nullcomponent()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_component.py#L262)

### [test_clock.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_clock.py)
- [x] Add td_x, exp_x and exp_idx_x to the start of the TestClock class definition, corresponding to the time domains of the new dummy Components, where 'x' is a currently unused letter of the alphabet in the other similar variables
- [x] Change the equivalent variables for the dumping to have the 'y' suffix (i.e. td_y etc.), where 'y' is the next letter in the alphabet to the suffix used in the above bullet point, making sure to also change all occurences of them (in can also just be any unused letter of the alphabet)
- [x] Add the new Component to the start of [**test_clock_init()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_clock.py#L38) and to the assertEqual statements below, using the variables created in the above 2 steps. 
- [x] Repeat for [**test_clock_iteration()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_clock.py#L59), change/add to the letters in the loop over clock, and the corresponding if and append statements
- [x] Repeat for [**test_clock_incompatible_time_domains()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_clock.py#L89)
- [x] Repeat for [**test_clock_incompatible_dumping_frequency()**](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_clock.py#L99)
- Note: td_{a,b,c,d,e,f,x,y} are derived from the get_dummy_timedomain function in [test_time.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_time.py) . If the function is changed, then td_a,b,c,d,e,f,x,y and thus exp_bool_a,b,c,d,e,f,x,y and exp_idx_a,b,c,d,e,f,x,y variables will need to be changed accordingly. 

### [test_record.py](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py)
- [x] Add in the expected records for the new Component for the
[same_t](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py#L11) and [diff_t](https://github.com/unifhy-org/unifhy/blob/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/test_utils/test_record.py#L35) tests, like for the other Components. This will depend on the values in the input files and any processing in the dummy nutrient Components.

### Dummy component files
- [x] Add in a new Component folder in [unifhy/tests/tests/components](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/tests/components) like for the other Components. Each folder needs to contain:
  - [x] an \_\_init\_\_.py file with just `from .dummy import Dummy` in it.
  - [x] a component_name.py file with some dummy transfers in it. The class that Dummy subclasses is the new Component class introduced in the unifhy/component.py 
  - [x] a dummyfortran folder with blank \_\_init\_\_.py file and a similar to the other Components
  - [x] a dummyc folder with blank \_\_init\_\_.py file and a Makefile & setup.py files similar to the other Components
- [x] Do the same for the Fortran versions, which involves: 
  - [x] a dummy.f90 file in the dummyfortran folder which:
    - [x] has separate variables for each state timestep
    - [x] x, y and the outputs are also in the subroutine definitions and declared within the subroutines
    - [x] All other inputs used in them declared at the start of the subroutines
    - [x] The same calculations as done in the python version (without the UnifHy routing function if it is used in the python version)
  - [x] Adding a Makefile in the dummyfortran folder, this is identical across Components
  - [x] Adding DummyFortran classes within the new Component dummy.py file. These pass the inputs and inwards to and receive the outputs and outwards from the Fortran subroutines, pass these to/from the exchanger, and perform any routing that needs doing, which can only be done from a python file. 
- [x] And for the C versions which involves:
  - [x] A dummy.c file containing the C code for the initialise/run/finalise functions
  - [x] A dummy.h file that just contains the declaration statements for the functions
  - [x] A dummy.pyx file that wraps the C initialise/run/finalise functions in the dummy.c file in python/cython code
  - [x] Adding DummyC classes within the new Component dummy.py file which call the initialise/run/finalise functions defined in the dummy.pyx files.
- [x] Add the dummy Fortran and C components to the Makefile in unifhy/tests/tests/components
- [x] Add new Components to the yaml files in [tests/configurations](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/configurations), copying the transfers/datasets/params etc. from the dummy Components.

### [Dummy data files](https://github.com/unifhy-org/unifhy/tree/8b774f584252f404c941166d634eeee6cf1cb71e/tests/data)
There also needs to be:
- [x] dummy data to fit the tests. I e. the inputs/outputs specified in the new dummy Components. 
- [x] Substitute data for when Components are tested as Data Components. These files need to have the outward transfers of the new Component in them. All the temporal and spatial resolution permutations also need to be covered, these are shown at the top of the test_component.py file. Thibault's data-generators scripts can generate the data files once the values and permutations are input. 

### unifhy.model
- [x] Add
```
xxxxxyyyyy: tests.components.xxxxxyyyyy.dummy
```
to the docstring of the [from_yaml](https://github.com/unifhy-org/unifhy/blob/5aa2e61b7abf4d44ffc50c097c63f53b2a53c128/unifhy/model.py#L231) method

xxxxxyyyyy  is the name given to the component by the name of the folder the dummy.py file resides in
